version: '3.8'

services:
  db_v1:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: v1
      MYSQL_DATABASE: DB_UCU_V1
      MYSQL_USER: v1
      MYSQL_PASSWORD: v1
    volumes:
      - db-data-v1:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db-data-v1:

