version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_HOST: mysql
    volumes: ['./backend:/app']

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BD1_Final

  redis:
    image: redis:latest